### ISSUE TITLE
Clean Clone + Yarn Test fails

### ISSUE THREAD

**Issue by fbartho** [apollographql/apollo-link-state#146]
# Observed Behavior
Cloning apollo-link-state, followed by calling `yarn run test` fails.

<details><summary>Console Log Failures from Lerna</summary>

```
[… snipped: hub clone apollographql/apollo-link-state]; cd apollo-link-state]
$ yarn test
yarn run v1.3.2
$ lerna run -- test
lerna info version 2.5.1
lerna info versioning independent
lerna ERR! test Errored while running script in 'apollo-link-state'
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: npm run test
lerna ERR! ● Validation Error:
lerna ERR! 
lerna ERR!   Module <rootDir>/node_modules/ts-jest/preprocessor.js in the transform option was not found.
lerna ERR! 
lerna ERR!   Configuration Documentation:
lerna ERR!   https://facebook.github.io/jest/docs/configuration.html
lerna ERR! 
lerna ERR! npm ERR! code ELIFECYCLE
lerna ERR! npm ERR! errno 1
lerna ERR! npm ERR! apollo-link-state@0.3.0 test: `jest`
lerna ERR! npm ERR! Exit status 1
lerna ERR! npm ERR! 
lerna ERR! npm ERR! Failed at the apollo-link-state@0.3.0 test script.
lerna ERR! npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
lerna ERR! npm WARN Local package.json exists, but node_modules missing, did you mean to install?
lerna ERR! 
lerna ERR! npm ERR! A complete log of this run can be found in:
lerna ERR! npm ERR!     /Users/fbarthelemy/.npm/_logs/2017-12-30T05_53_36_993Z-debug.log
lerna ERR! 
lerna ERR! > apollo-link-state@0.3.0 test /Users/fbarthelemy/Code/apollo-link-state/packages/apollo-link-state
lerna ERR! > jest
lerna ERR! 
lerna ERR! 
lerna ERR!     at Promise.all.then.arr (/Users/fbarthelemy/Code/apollo-link-state/node_modules/execa/index.js:236:11)
lerna ERR!     at <anonymous>
(node:32631) UnhandledPromiseRejectionWarning: Error: Command failed: npm run test
● Validation Error:

  Module <rootDir>/node_modules/ts-jest/preprocessor.js in the transform option was not found.

  Configuration Documentation:
  https://facebook.github.io/jest/docs/configuration.html

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! apollo-link-state@0.3.0 test: `jest`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the apollo-link-state@0.3.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/fbarthelemy/.npm/_logs/2017-12-30T05_53_36_993Z-debug.log

> apollo-link-state@0.3.0 test /Users/fbarthelemy/Code/apollo-link-state/packages/apollo-link-state
> jest


    at Promise.all.then.arr (/Users/fbarthelemy/Code/apollo-link-state/node_modules/execa/index.js:236:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
(node:32631) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:32631) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
</details>

- Running `yarn run jest` also fails due to some missing dependencies.

# Expected Behavior

Off of a clean clone, it should be possible to run the test-suite for apollo-link-state, or further documentation should be provided on how to do so.

**Comment by peggyrayzis** [comment]
Did you run `yarn run bootstrap` first?

**Comment by fbartho** [comment]
I did not, I only now noticed that script was there. Thanks for the hint @peggyrayzis 

After the bootstrap, I ran `yarn run test` and it looks like `lerna` is hung ![screenshot](https://cl.ly/1d1B3b3b1m3j/Image%202018-01-09%20at%2012.07.25%20PM.png)

**Comment by peggyrayzis** [comment]
Weird, it works for me 🤷‍♀️

**Comment by peggyrayzis** [comment]
Lerna has been causing issues lately, especially w/ deployment. I'm thinking of removing it soon.

**Comment by fbartho** [comment]
It was still hung an hour later. I killed and retried, but no dice.

Maybe we should switch to yarn workspaces? (I know nothing about them but what the [blog](https://yarnpkg.com/blog/2017/08/02/introducing-workspaces/) says)

**Comment by hwillson** [comment]
Thanks for reporting this @fbartho! Given that we're planning on merging `apollo-link-state`'s functionality into `apollo-client` directly (in the not too distant future), we aren't going to be addressing outstanding project infrastructure items like this (since this infrastructure will be removed when this repo's functionality is moved into `apollo-client`). Closing for now - thanks again!
