### ISSUE TITLE
Next.js + link-state + SSR

### ISSUE THREAD

**Issue by f2net** [apollographql/apollo-link-state#185]
I receive an error when using apollo-link-state with Next.js/Apollo (modifying the "with Apollo" example in Next.js repository). I'm not sure it is an issue really: I may be missing something.
See the original "with Apollo" example:
https://github.com/zeit/next.js/tree/canary/examples/with-apollo

Here's my code for initApollo:

```javascript
import { ApolloClient } from 'apollo-client'
import { HttpLink } from 'apollo-link-http'
import { InMemoryCache } from 'apollo-cache-inmemory'
import fetch from 'isomorphic-fetch'

import { ApolloLink } from 'apollo-link'
import { withClientState } from 'apollo-link-state'

import config from '../config'

let apolloClient = null

// Polyfill fetch() on the server (used by apollo-client)
if (!process.browser) {
  global.fetch = fetch
}

const cache = new InMemoryCache()

const defaultState = {
  currentView: {
    __typename: 'CurrentView',
    view: 'list'
  }
}

const stateLink = withClientState({
  cache,
  defaults: defaultState
  // resolvers: {
  //   Mutation: {
  //     switchView: (_, { currentView }, { cache }) => {
  //       const query = gql`
  //         query getCurrentView {
  //           getCurrentView @client {
  //             currentView
  //           }
  //         }
  //       `
  //       const previous = cache.readQuery({ query })
  //       const data = {
  //         currentView: {
  //           ...previous.currentView,
  //           currentView: view
  //         }
  //       }

  //       cache.writeQuery({ query, data })
  //     }
  //   }
  // }
})

function create (initialState) {
  return new ApolloClient({
    connectToDevTools: process.browser,
    ssrMode: !process.browser, // Disables forceFetch on the server (so queries are only run once)
    link: ApolloLink.from([
      stateLink,
      new HttpLink({
        uri: config.apiUrl,
        opts: {
          credentials: 'same-origin' // Additional fetch() options like `credentials` or `headers`
        }
      })
    ]),
    cache: cache.restore(initialState || {}),
  })
}

export default function initApollo (initialState) {
  // Make sure to create a new client for every server-side request so that data
  // isn't shared between connections (which would be bad)
  if (!process.browser) {
    return create(initialState)
  }

  // Reuse client on the client-side
  if (!apolloClient) {
    apolloClient = create(initialState)
  }

  return apolloClient
}
```

Then I have a gql query in getCurrentView.js:
```javascript
import gql from 'graphql-tag'

export default gql`
  query getCurrentView {
    currentView @client {
      view
    }
  }
```

And then I have the component composed with withData (the same file as in the Next.js example), the http queries and the local query:
```javascript
import { Component } from 'react'
import withData from '../../lib/withData'

import config from '../../config'

import { graphql, compose } from 'react-apollo'
import allProducts from '../../graphql/allProducts'
import getCategoryBySeoName from '../../graphql/getCategoryBySeoName'
import { getCurrentView } from '../../graphql'
// [other imports cut...]

class Categoria extends Component {
//...
}

export default compose(
  withData,
  graphql(getCurrentView, {
    name: 'currentView'
  }),
  graphql(allProducts, {
    name: 'allProducts',
    options: ({ url }) => ({ variables: { categorySeoName: url.query.categorySeoName, limit: config.itemsPerPage, offset: 0 } })
  }),
  graphql(getCategoryBySeoName, {
    name: 'getCategoryBySeoName',
    options: ({ url }) => ({ variables: { seoName: url.query.categorySeoName } })
  })
)(Categoria)

```

I receive the following error:
```
Unhandled (in react-apollo:Apollo(Apollo(Apollo(Categoria)))) Error: Network error: Cannot read property 'Query' of undefined
    at new ApolloError (http://localhost:3001/_next/1517221068041/page/categoria.js:21154:28)
    at ObservableQuery.module.exports.ObservableQuery.currentResult (http://localhost:3001/_next/1517221068041/page/categoria.js:20361:24)
    at GraphQL.dataForChild (http://localhost:3001/_next/1517221068041/page/categoria.js:18856:62)
    at GraphQL.render (http://localhost:3001/_next/1517221068041/page/categoria.js:18906:33)
    at finishClassComponent (http://localhost:3001/_next/1517221068041/commons.js:7879:31)
    at updateClassComponent (http://localhost:3001/_next/1517221068041/commons.js:7856:12)
    at beginWork (http://localhost:3001/_next/1517221068041/commons.js:8231:16)
    at performUnitOfWork (http://localhost:3001/_next/1517221068041/commons.js:10230:16)
    at workLoop (http://localhost:3001/_next/1517221068041/commons.js:10294:26)
    at HTMLUnknownElement.callCallback (http://localhost:3001/_next/1517221068041/commons.js:548:14)
```

Thank you very much for your support.
If I can find a way to solve this issue I may post a PR for a "with Apollo and apollo-link-state" on Next.js.

**Comment by dav-is** [comment]
I'm experiencing the exact same issue.

**Comment by kedarguy** [comment]
Hey, I also set apollo-link-state with next.js, I think you are missing the "resolver" in the query (Im not sure if that is the right term)

my default state: 
```
defaults: {
      scroll: {
        direction: null,
        velocity: null,
        x: 0,
        y: 0,
        __typename: 'Scroll',
      },
    },
```

```
const Scroll_QUERY = gql`
  query {
    scroll @client {
      x
      y
    }
  }
`;
```

```
const WrappedScrollDisplay = graphql(Scroll_QUERY, {
  props: ({ data, }) => data,
})(ScrollDisplay);

export default WrappedScrollDisplay;
```

**Comment by kedarguy** [comment]
I am also using apollo-link-state with next, I think your problem is probably related to tryng to call @client on the server, you need to use dynamic import o exclude the component from rendering on the server.

here is my setup in case there are other issues:

```
import { ApolloClient, } from 'apollo-client';
import { HttpLink, InMemoryCache, ApolloLink, } from 'apollo-client-preset';
import { withClientState, } from 'apollo-link-state';
import fetch from 'isomorphic-unfetch';
import config from 'config';

const hostIp = config.get('hostIp');
let apolloClient = null;

// Polyfill fetch() on the server (used by apollo-client)
if (!process.browser) {
  global.fetch = fetch;
}

function create(initialState) {
  const link = new HttpLink({
    uri: `http://${hostIp}:3000/graphql`, // Server URL (must be absolute)
    opts: {
      credentials: 'same-origin', // Additional fetch() options like `credentials` or `headers`
    },
  });

  const cache = new InMemoryCache({
    dataIdFromObject: ({ __typename, contentId, }) =>
      (contentId ? `${__typename}:${contentId}` : null),
  }).restore(initialState || {});

  const stateLink = withClientState({
    cache,
    defaults: {
      scroll: {
        direction: null,
        velocity: null,
        x: 0,
        y: 0,
        __typename: 'Scroll',
      },
    },
    resolvers: {
      Mutation: {
        updateScroll: (_, { x, y, direction, velocity, }, { cache, }) => {
          const data = {
            scroll: {
              direction,
              velocity,
              x,
              y,
              __typename: 'Scroll',
            },
          };
          cache.writeData({ data, });
          // resolver needs to return something / null https://github.com/apollographql/apollo-link-state/issues/160
          return null;
        },
      },
    },
  });

  return new ApolloClient({
    connectToDevTools: process.browser,
    ssrMode: !process.browser, // Disables forceFetch on the server (so queries are only run once)
    link: ApolloLink.from([ stateLink, link, ]),
    cache,
    queryDeduplication: true,
  });
}

export default function initApollo(initialState) {
  // Make sure to create a new client for every server-side request so that data
  // isn't shared between connections (which would be bad)
  if (!process.browser) {
    return create(initialState);
  }

  // Reuse client on the client-side
  if (!apolloClient) {
    apolloClient = create(initialState);
  }
  return apolloClient;
}
```

```
import React from 'react';
import PropTypes from 'prop-types';
import { graphql, } from 'react-apollo';
import gql from 'graphql-tag';

const Scroll_QUERY = gql`
  query {
    scroll @client {
      x
      y
    }
  }
`;

function ScrollDisplay({ loading, error, scroll, render, }) {
  if (loading) return <div>Loading ...</div>;
  if (error) return <div>Error</div>;
  if (scroll) {
    return render(scroll);
  }
}

ScrollDisplay.propTypes = propTypes;
ScrollDisplay.defaultProps = defaultProps;

const WrappedScrollDisplay = graphql(Scroll_QUERY, {
  props: ({ data, }) => data,
})(ScrollDisplay);

export default WrappedScrollDisplay;
```

dynamiclly import only in no ssr mode


```
import dynamic from 'next/dynamic';
const DynamicScrollDisplay = dynamic(import('../components/EventListener/ScrollDisplay'), {
  ssr: false,
});

<DynamicScrollDisplay
            render={scroll => (
              <div
                style={{ position: 'sticky', top: '-5px', float: 'right', display: 'inline-block', }}
              >
                scroll x: {scroll.x} scroll y: {scroll.y}
              </div>
            )}
        />


```

**Comment by dav-is** [comment]
Is there a reason why you can’t use a local store on the server side? The state is created upon request, then transferred to the client after render.

**Comment by kedarguy** [comment]
I think the local store uses the cache on the client side which you can't query on the server side.

This is from the apollo docs:

> In the past, Apollo users stored their application’s local data in a separate Redux or MobX store. With apollo-link-state, you no longer have to maintain a second store for local state. You can instead use the Apollo Client cache as your single source of truth that holds all of your local data alongside your remote data. To access or update your local state, you use GraphQL queries and mutations just like you would for data from a server.

[https://www.apollographql.com/docs/link/links/state.html](https://www.apollographql.com/docs/link/links/state.html)

**Comment by f2net** [comment]
I agree with dav-is: the initial state of apollo-link-state should be created on the server, too and passed to client. All the @client queries should simply be skipped server-side.
Since Next.js + Apollo + apollo-link-state is a great stack, it would be useful to have a working example "with apollo-link-state" on the Next.js repository by the Apollo staff :) @peggyrayzis

**Comment by dav-is** [comment]
I don’t think @client queries should be ignored on the server. The server has everything it needs to run these queries. We set a default in the store on the server and our query and mutation resolvers are define in code that the server has access to.

**Comment by timhuff** [comment]
@dav-is While technically feasible, wouldn't this encounter massive scaling issues? You'd be keeping the entire state of all your users on the server. Either that or have the problem of having to hit the DB every time you want to change something in the user's state. Seems that db-backed user state should be part of some sort of User db object but that this should not be one in the same with the apollo state. The apollo state seems like it should fulfill the same purpose as the redux state - a manageable, local, global state for the client.

**Comment by dav-is** [comment]
> @timhuff You'd be keeping the entire state of all your users on the server

The state is reset on every request. Client queries aren’t database calls. And with SSR, client queries would only be setting defaults as it’s the beginning of a request chain. All other client actions would be done in the browser.

**Comment by timhuff** [comment]
@dav-is I see. I was misunderstanding how this would work.

**Comment by f2net** [comment]
I ended up using Redux for the local state of my Next.js application. I'll switch back to apollo-link-state as soon as I find a good way to use it (or a working example without dynamic import hacks) @peggyrayzis

**Comment by razor-x** [comment]
I was surprised to find there is difficulty supporting this. I expected it would be transparent to next.js. 

Perhaps the confusion here is that the terms "server" and "client" are getting overloaded. We have

- The graphql server: responds to graphql requests.
- The Next.js server: renders the app and sends it to the browser client. (This server "pretends" to act like a browser client: it's really isomorphic to it 😉)
- The browser client: fully able to render the app from scratch or pick up from a server-rendered app.
- The `@client` state and queries: the part of the apollo-cache that does not make network requests to the graphql server.

@dav-is Would this be direct analogy to redux SRR?

1. The data normally in the redux store is now moved into part of the the apollo-cache, it's just "tagged" with `@client` to indicate it's not connected to a remote graphql server schema.
2. The "queries" and "mutations" on the `@client` fields correspond to to reading data from the redux store or dispatching classical ("non-async") actions that result in updates to the store. Now, they just read or update `@client` fields in the apollo-cache.
3. The only difference between these `@client` queries and the "normal" ones are that they do not hit the network, otherwise the result is the same: data read from or written to the apollo-cache.
4. Thus, the `@client` queries work the same on the client or the server, and instead of having to send a separate redux store down to the client after SSR, all that state is now contained in the apollo-cache, which we are shipping down anyway.

**Comment by leoalves** [comment]
I was able to make this work with the skip option.

`
export default compose(
  withData,
  graphql(getCurrentView, {
    name: 'currentView',
    skip: typeof window === 'undefined'
  })
)(Categoria)
`

**Comment by dav-is** [comment]
Isn’t that just going to disable the query on the server side? What’s the point in SSR if it can’t render everything on the server?

**Comment by leoalves** [comment]
Hi @dav-is,

I agree with you that the server has everything it needs and should run @client queries/mutations.  

I was just posting a different solution since @f2net  solved it by keeping redux.  If he is only using it for the client, maybe he doesn't need to keep redux and can skip the @client queries on the server.

At least in my case, I only needed it to run in the browser and was able to remove redux.

**Comment by f2net** [comment]
Thank you @leoalves, on the next refactoring I'll give a new chance to apollo-link-state using your trick.

**Comment by fbartho** [comment]
Looks like actions were taken here, so I'm going to close this issue!

**Comment by dav-is** [comment]
@fbartho link to the fix?

**Comment by fbartho** [comment]
@dav-is Up in this thread @leoalves suggested a work-around, and others suggested that separate Feature Requests should be made for adding SSR friendliness to apollo-link-state.

This specific ticket doesn’t have any pending action items — as I read the thread. Please let me know if I misunderstood!

**Comment by dav-is** [comment]
@fbartho the issue is the error thrown in the very first post in the issue. The further discussion talks about workarounds to the general issue, but no actual solutions.

**Comment by fbartho** [comment]
@dav-is Reopening because I didn't understand :P

**Comment by hollandThomas** [comment]
@leoalves I tried your approach with the new `react-apollo` Query Component like this

```javascript
<Query
   query={gql`
        {
          viewer(id: "0x2") {
            id
            email
          }
          authenticated @client
        }
  `}
  skip={typeof window === 'undefined'}
>
  {({ loading, error, data }) => {
    if (loading) return <p>Loading...</p>;
    if (error) {
      console.log(error);
      return <p>Error :(</p>;
    }
    return <p>{data.viewer.email}</p>;
  }}
</Query>
```

Unfortunately this does not work for me. Any ideas?

Also, will there be an official solution to this problem without workarounds? Thanks!

**Comment by leoalves** [comment]
@hollandThomas I won't be much help here since I never used the Query Component.

But I guess you can always skip before you render the component.

```
{
typeof window !==  undefined && <Query
   query={gql`
    {
      viewer(id: "0x2") {
        id
        email
      }
      authenticated @client
    }
  `}
>
  {({ loading, error, data }) => {
    if (loading) return <p>Loading...</p>;
    if (error) {
      console.log(error);
      return <p>Error :(</p>;
    }
    return <p>{data.viewer.email}</p>;
  }}
</Query>
}
```

If that doesn't work the issue is not the skip but something else.

**Comment by brad-decker** [comment]
Really curious about this, I made the switch to Apollo with this as one of the real winning benefits (being able to derive initial client state from getDataFromTree). Seems like that isn't the case yet. Whats the plan for implementing this? Any work arounds or custom implementations to get this feature on the server in userland?

**Comment by brad-decker** [comment]
In case anyone else wonders about this I was able to get this working with SSR by just not passing the defaults key when rehydrating. if defaults are set the link will write the defaults to cache overwriting your rehydration.

**Comment by msreekm** [comment]
@brad-decker ,did you mean we don't have to bypas SSR with apollo-link-state anymore? do you have an example code ?

**Comment by ellioseven** [comment]
@brad-decker I tried something like:

```
const clientState = (typeof window === "undefined")
  ? { defaults, resolvers }
  : { resolvers }
return new ApolloClient({
  cache,
  clientState,
  uri: config.endpoint
})
```

But that didn't work. Is it possible to show us your example please?

**Comment by ellioseven** [comment]
I noticed that when using `writeData` directly will add local data to the cache on `getInitialProps` (SSR):

```js
static async getInitialProps ({ apolloClient }) {
  apolloClient.writeData({
    data: {
      breadcrumbs: {
        __typename: "Breadcrumbs",
        items: ["one", "two", "three"]
      }
    }
  })

  const previous = apolloClient.readQuery({
    query: gql`{ breadcrumbs { items } }`
  })

  apolloClient.writeData({
    data: {
      breadcrumbs: {
        __typename: "Breadcrumbs",
        items: [ ...previous.breadcrumbs.items, "four", "five" ]
      }
    }
  })
  
  return {}
}
```

Not great but it seems like it could be a work around?

**Comment by shawnmmatthews** [comment]
@brad-decker I'd also be super interested in example code.

**Comment by shawnmmatthews** [comment]
Has anyone made any progress on this?

**Comment by richbai90** [comment]
I have this working following the official next.js example repo. Give me a few minutes to make a gist and I'll post it. It's in TS though.

**Comment by richbai90** [comment]
This is working for me currently, but I haven't implemented mutations yet. https://gist.github.com/richbai90/98011174f66ed275d9531ea5813bf4a2

**Comment by shawnmmatthews** [comment]
Thanks at @richbai90 that helped a-lot. I have it up and going now. Just a note a "resolvers: {}" object seems to be necessary for stateLink to work. I think the docs mention you only need to declare the defaults object, but I needed both to get this working.

**Comment by brad-decker** [comment]
this is what I have. Sorry for the delay:

in my store/ folder I have setup a single entry point that merges configuration objects from different files. config.defaults is the overall default object to write to the store. 

```js
export const createStateLink = (cache: InMemoryCache) => {
  // this function will be used to seed state and to reset it when necessary
  const writeDefaults = () => {
    cache.writeData({ data: config.defaults });
  };

  const link = withClientState({
    resolvers: config.resolvers,
    typeDefs,
    cache,
  });

  return {
    link,
    writeDefaults,
  };
};
```

then in my Apollo client initializer utility: 
```js
  // initialize our local state with apollo-link-state.
  const { link: stateLink, writeDefaults } = createStateLink(cache);
  if (!initialState) {
    /**
     * withClientState has a 'defaults' key that you think would
     * be a good way of setting your default state. That's true,
     * only if you want to override the existing values from SSR
     * on the initial client side render.
     *
     * Under the hood, apollo-link-state just calls
     * cache.writeData({ data: defaults }) when default is set
     * regardless of whether data exists yet or not.
     */
    writeDefaults();
  }
  const client = new ApolloClient({
    connectToDevTools: process.browser,
    shouldBatch: true,
    ssrMode: !process.browser,
    link: ApolloLink.from([
      stateLink,
      authLink,
      persistedQueryLink.concat(httpLink),
    ]),
    cache,
  });

  // When reseting the store, write the defaults to the state tree.
  client.onResetStore(writeDefaults);

  return client;
```

**Comment by sakhmedbayev** [comment]
@richbai90 @brad-decker I do not quite understand, do you example allow ssr `@client` queries?

**Comment by richbai90** [comment]
yes it does

**Comment by puneetv05** [comment]
@richbai90  thanks for the workaround ! can you explain, what actually does your code does? does it solves the main issue that we facing with @client on SSR and what if we want to call the @client on the browser only ( we want to access localstorage etc).

**Comment by Matfork** [comment]
With apollo-client v2.5, apollo-link-state was merged into main apollo-client lib. 
So now, everything is handled with apollo-client and we don't need to rely on 'stateLink'.

Right now I'm testing initial data load in a page component via getInitialProps(ctx)

```typescript
 static async getInitialProps(ctx: any) {
    const {
      apolloClient
    }: { apolloClient: ApolloClient<NormalizedCacheObject> | null } = ctx;

    if (apolloClient) {
     const data = await apolloClient.query({
        query: CATALOG_QUERIES.SQ_GET_POSTS,
        variables: { last: 10 }
      });
      console.log('post-page, graphql data loaded', data);

      const data2 = await apolloClient.query({
        query: CATALOG_QUERIES.CQ_GET_VARS
      });
      console.log('post-page, graphql data loaded @client', data2);
    }

    return {};
  }
```

And using two queries, one server-side and the other client-side (@client)
```typescript
export const CATALOG_QUERIES = {
  SQ_GET_POSTS: gql`
    query AllPosts($last: Int) {
      allPosts(last: $last) {
        id
        title
        text
        createdAt
      }
    }
  `,
  CQ_GET_VARS: gql`
    query Cli_get_vars {
      cli_get_vars @client {
        counter
        counter2
      }
    }
  `
};,
```

When page loads it works without any problem, which is good.
I don't know if v2.5 (which uses ssr flag) solved the link-state srr issue, but I think it can be an option to consider.

**Comment by tafelito** [comment]
I'm having the same issue and if I understood correctly @brad-decker is doing is writing defaults values on the cache before is actually initialized. My problem is that the @client resolver depends on values of a different query. So a query has to be executed in the server, I need those values in the cache, and then the client resolver would know what to return.

So pretty much I have this query 
```gql
 query product($id: ID!) {
    product(where: { id: $id }) {
      isInCart @client
      ...ProductData
    }
  }
```
in order to return the correct value in the isInCart resolver, I need the data of the product first, and I only have the data when the product query is run on the server the first time. I can't write defaults because I don't have them. 

I'm using apollo-client 2.5
