### ISSUE TITLE
Unable to get cacheResolver to work with link state

### ISSUE THREAD

**Issue by scraperg** [apollographql/apollo-link-state#190]
Hi,

Do cacheResolvers (https://www.apollographql.com/docs/react/features/cache-updates.html#cacheRedirect) work with apollo-link-state? I haven't been able to find any reference to them in the link state documentation.

I have a nested structure stored in link state, that I'd like to be able to query "into" using a cacheResolver, or something similar.

~~My cacheResolver implementation is similar to the example in the documentation, but no query result is included in the graphql HOC props callback. And writeToStore.js logs warnings like "Missing field id in {}" to the console. But there are no logged errors/exceptions.~~

I was able to implement a similar query using readFragment, but I haven't found a way to use readFragment from the graphql HOC. So I can't use readFragment as a substitute (as far as I can tell).

Any advice appreciated. Thanks.

**Edit** I did have an issue around setting up the cacheResolvers. Now I get the following error in the console:

```
DOMException: Failed to execute 'postMessage' on 'Window': TypeError: Cannot read property 'myCacheResolver' of undefined could not be cloned.
    at ApolloClient.hookLogger [as devToolsHookCb] (<anonymous>:14:14)
    at QueryManager.onBroadcast (http://localhost:8080/app.bundle.js:31374:27)
    at QueryManager.broadcastQueries (http://localhost:8080/app.bundle.js:32083:14)
    at http://localhost:8080/app.bundle.js:31659:31
    at <anonymous>
	
react-apollo.browser.umd.js:545 Unhandled (in react-apollo:Apollo(WeeksContainer)) Error: Network error: Cannot read property 'myCacheResolver' of undefined
    at new ApolloError (http://localhost:8080/app.bundle.js:5334:28)
    at ObservableQuery.currentResult (http://localhost:8080/app.bundle.js:4798:24)
    at GraphQL.dataForChild (http://localhost:8080/app.bundle.js:3475:62)
    at GraphQL.render (http://localhost:8080/app.bundle.js:3525:33)
    at finishClassComponent (http://localhost:8080/app.bundle.js:22010:31)
    at updateClassComponent (http://localhost:8080/app.bundle.js:21987:12)
    at beginWork (http://localhost:8080/app.bundle.js:22362:16)
    at performUnitOfWork (http://localhost:8080/app.bundle.js:24361:16)
    at workLoop (http://localhost:8080/app.bundle.js:24425:26)
    at HTMLUnknownElement.callCallback (http://localhost:8080/app.bundle.js:14679:14)
```

**Comment by scraperg** [comment]
Never mind. I was able to get it working.

Thanks.
