### ISSUE TITLE
feat(graphql): Added TGraphQLVariables type

### ISSUE THREAD

**Issue by jbaxleyiii** [apollographql/apollo-link-state#27]
Added a type generic to the graphql function named TGraphQLVariables.
It allows for specifying types that are required for the query that
should NOT be passed to the underlying component but are just used
for the GraphQL operation. The type is joined to the component's TProps
but not required on the passed in component.

Per apollographql/apollo-client#2198

This should not effect any current implementations as it defaults to `{}`.

I need a sanity check on type inference in this case. I know that typescript does not currently do partial type inference, but I'm pretty sure that it will use default types when type inference is not possible. Someone might want to confirm that as it would be pretty unfortunate if someone were depending on type inference and this change somehow let their type unspecifyable (I don't know how that would occur, but would rather not cause someone an afternoon of type bugs).

### Checklist:
* [x] If this PR is a new feature, please reference an issue where a consensus about the design was reached (not necessary for small changes)
* [x] Make sure all of the significant new logic is covered by tests
* [x] If this was a change that affects the external API used in GitHunt-React, update GitHunt-React and post a link to the PR in the discussion.

There were some failing checks when I pulled the master branch. I took note of both the compile and test results before and after my changes and am including them here in case Travis complains.

Compile state prior to change:

```
jdstewar@LMC-056682 react-apollo (master) $ yarn compile
yarn run v1.1.0
$ tsc
$ npm run bundle

> react-apollo@1.4.16 bundle /Users/jdstewar/gitRepo/react-apollo
> rollup -c && rollup -c rollup.browser.config.js && rollup -c rollup.test-utils.config.js

The following options have been renamed — please update your config: options.entry -> options.input, options.moduleName -> options.name, options.sourceMap -> options.sourcemap, options.dest -> options.output.file, options.format -> options.output.format

lib/index.js → lib/react-apollo.umd.js...
No name was provided for external module 'react' in options.globals – guessing 'React'
No name was provided for external module 'prop-types' in options.globals – guessing 'PropTypes'
No name was provided for external module 'redux' in options.globals – guessing 'redux'
No name was provided for external module 'apollo-client' in options.globals – guessing 'apolloClient'
No name was provided for external module 'graphql-tag' in options.globals – guessing 'graphqlTag'
No name was provided for external module 'react-dom/server' in options.globals – guessing 'ReactDOM'
created lib/react-apollo.umd.js in 119ms
The following options have been renamed — please update your config: options.entry -> options.input, options.moduleName -> options.name, options.sourceMap -> options.sourcemap, options.dest -> options.output.file, options.format -> options.output.format

lib/browser.js → lib/react-apollo.browser.umd.js...
No name was provided for external module 'react' in options.globals – guessing 'React'
No name was provided for external module 'prop-types' in options.globals – guessing 'PropTypes'
No name was provided for external module 'redux' in options.globals – guessing 'redux'
No name was provided for external module 'apollo-client' in options.globals – guessing 'apolloClient'
No name was provided for external module 'graphql-tag' in options.globals – guessing 'graphqlTag'
created lib/react-apollo.browser.umd.js in 101ms
The following options have been renamed — please update your config: options.entry -> options.input, options.moduleName -> options.name, options.sourceMap -> options.sourcemap, options.dest -> options.output.file, options.format -> options.output.format

lib/test-utils.js → lib/test-utils.js...
No name was provided for external module 'react' in options.globals – guessing 'React'
No name was provided for external module 'apollo-client' in options.globals – guessing 'ApolloClient'
No name was provided for external module 'graphql' in options.globals – guessing 'graphql'
No name was provided for external module 'prop-types' in options.globals – guessing 'PropTypes'
created lib/test-utils.js in 66ms
✨  Done in 2.62s.
```

Test state prior to change:

    Summary of all failing tests
     FAIL  test/react-web/server/index.test.tsx
      ● SSR › `getDataFromTree` › shouldn't run queries if ssr is turned to off
    
        expect(received).toEqual(expected)
    
        Expected value to equal:
          {}
        Received:
          undefined
    
        Difference:
    
          Comparing two different types of values. Expected object but received undefined.
    
          at test/react-web/server/index.test.tsx:515:53
          at tryCallOne (node_modules/promise/lib/core.js:37:12)
          at node_modules/promise/lib/core.js:123:15
          at flush (node_modules/asap/raw.js:50:29)
          at _combinedTickCallback (internal/process/next_tick.js:131:7)
          at process._tickCallback (internal/process/next_tick.js:180:9)
    
     FAIL  test/react-web/client/graphql/queries/index.test.tsx (6.582s)
      ● queries › stores the component name in the query metadata
    
        Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
    
          at pTimeout (node_modules/jest-jasmine2/build/queueRunner.js:53:21)
          at ontimeout (timers.js:469:11)
          at tryOnTimeout (timers.js:304:5)
          at Timer.listOnTimeout (timers.js:264:5)
    
     FAIL  test/react-web/client/graphql/queries/loading.test.tsx (7.682s)
      ● [queries] loading › correctly sets loading state on remounted network-only query
    
        Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
    
          at pTimeout (node_modules/jest-jasmine2/build/queueRunner.js:53:21)
          at ontimeout (timers.js:469:11)
          at tryOnTimeout (timers.js:304:5)
          at Timer.listOnTimeout (timers.js:264:5)
    
    
    Test Suites: 3 failed, 24 passed, 27 total
    Tests:       3 failed, 169 passed, 172 total
    Snapshots:   1 passed, 1 total
    Time:        10.333s
    Ran all test suites.Compile after changes:

```
jdstewar@LMC-056682 react-apollo (master) $ yarn compile
yarn run v1.1.0
$ tsc
$ npm run bundle

> react-apollo@1.4.16 bundle /Users/jdstewar/gitRepo/react-apollo
> rollup -c && rollup -c rollup.browser.config.js && rollup -c rollup.test-utils.config.js

The following options have been renamed — please update your config: options.entry -> options.input, options.moduleName -> options.name, options.sourceMap -> options.sourcemap, options.dest -> options.output.file, options.format -> options.output.format

lib/index.js → lib/react-apollo.umd.js...
No name was provided for external module 'react' in options.globals – guessing 'React'
No name was provided for external module 'prop-types' in options.globals – guessing 'PropTypes'
No name was provided for external module 'redux' in options.globals – guessing 'redux'
No name was provided for external module 'apollo-client' in options.globals – guessing 'apolloClient'
No name was provided for external module 'graphql-tag' in options.globals – guessing 'graphqlTag'
No name was provided for external module 'react-dom/server' in options.globals – guessing 'ReactDOM'
created lib/react-apollo.umd.js in 120ms
The following options have been renamed — please update your config: options.entry -> options.input, options.moduleName -> options.name, options.sourceMap -> options.sourcemap, options.dest -> options.output.file, options.format -> options.output.format

lib/browser.js → lib/react-apollo.browser.umd.js...
No name was provided for external module 'react' in options.globals – guessing 'React'
No name was provided for external module 'prop-types' in options.globals – guessing 'PropTypes'
No name was provided for external module 'redux' in options.globals – guessing 'redux'
No name was provided for external module 'apollo-client' in options.globals – guessing 'apolloClient'
No name was provided for external module 'graphql-tag' in options.globals – guessing 'graphqlTag'
created lib/react-apollo.browser.umd.js in 106ms
The following options have been renamed — please update your config: options.entry -> options.input, options.moduleName -> options.name, options.sourceMap -> options.sourcemap, options.dest -> options.output.file, options.format -> options.output.format

lib/test-utils.js → lib/test-utils.js...
No name was provided for external module 'react' in options.globals – guessing 'React'
No name was provided for external module 'apollo-client' in options.globals – guessing 'ApolloClient'
No name was provided for external module 'graphql' in options.globals – guessing 'graphql'
No name was provided for external module 'prop-types' in options.globals – guessing 'PropTypes'
created lib/test-utils.js in 66ms
✨  Done in 2.53s.
```

Tests after changes:

    Summary of all failing tests
     FAIL  test/react-web/server/index.test.tsx
      ● SSR › `getDataFromTree` › shouldn't run queries if ssr is turned to off
    
        expect(received).toEqual(expected)
    
        Expected value to equal:
          {}
        Received:
          undefined
    
        Difference:
    
          Comparing two different types of values. Expected object but received undefined.
    
          at test/react-web/server/index.test.tsx:515:53
          at tryCallOne (node_modules/promise/lib/core.js:37:12)
          at node_modules/promise/lib/core.js:123:15
          at flush (node_modules/asap/raw.js:50:29)
          at _combinedTickCallback (internal/process/next_tick.js:131:7)
          at process._tickCallback (internal/process/next_tick.js:180:9)
    
     FAIL  test/react-web/client/graphql/queries/index.test.tsx (6.166s)
      ● queries › stores the component name in the query metadata
    
        Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
    
          at pTimeout (node_modules/jest-jasmine2/build/queueRunner.js:53:21)
          at ontimeout (timers.js:469:11)
          at tryOnTimeout (timers.js:304:5)
          at Timer.listOnTimeout (timers.js:264:5)
    
     FAIL  test/react-web/client/graphql/queries/loading.test.tsx (7.18s)
      ● [queries] loading › correctly sets loading state on remounted network-only query
    
        Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
    
          at pTimeout (node_modules/jest-jasmine2/build/queueRunner.js:53:21)
          at ontimeout (timers.js:469:11)
          at tryOnTimeout (timers.js:304:5)
          at Timer.listOnTimeout (timers.js:264:5)
    
    
    Test Suites: 3 failed, 24 passed, 27 total
    Tests:       3 failed, 169 passed, 172 total
    Snapshots:   1 passed, 1 total
    Time:        9.054s
    Ran all test suites.

**Comment by jbaxleyiii** [comment]
➤ meteor-bot commented:

@dyst5422: Thank you for submitting a pull request! Before we can merge it, you'll need to sign the Meteor Contributor Agreement here: https://contribute.meteor.com/

**Comment by jbaxleyiii** [comment]
➤ meteor-bot commented:



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

No CHANGELOG added.
  </td>
    </tr>
  </tbody>
</table>

<p align="right">
  Generated by :no_entry_sign: [dangerJS](http://github.com/danger/danger-js/)
</p>
