### ISSUE TITLE
Cannot read property 'Query' of undefined when combining local state queries with network

### ISSUE THREAD

**Issue by stolinski** [apollographql/apollo-link-state#273]
I'm using Apollo Boost to configure, my setup is very basic.

```
const defaultState = {
  isEditMode: false
};

// Connecting out site to the GraphQL API
const client = new ApolloClient({
  uri: 'https://api-uswest.graphcms.com/v1/cjjoov78z2j9t01gclcnhwlb9/master',
  clientState: {
    defaults: defaultState
  }
});
```

the problem lies when trying to query both @client and a network query. 

```
  query post($id: ID!) {
    post(where: { id: $id }) {
      id
      title
      body
    }
    isEditMode @client
  }
```

causes an odd error of "Cannot read property 'Query' of undefined"

I know state is working somewhat because both

```
  query post($id: ID!) {
    post(where: { id: $id }) {
      id
      title
      body
    }
  }
```
and 
```
  query post($id: ID!) {
    isEditMode @client
  }
```

return the correct data, but when using them together causes this error. A full log of the error in Apollo Dev tools is

```
"TypeError: Cannot read property 'Query' of undefined\n    at resolver (http://localhost:3000/static/js/bundle.js:5576:44)\n    at http://localhost:3000/static/js/bundle.js:9158:46\n    at step (http://localhost:3000/static/js/bundle.js:9039:27)\n    at Object.next (http://localhost:3000/static/js/bundle.js:9020:57)\n    at http://localhost:3000/static/js/bundle.js:9014:75\n    at new Promise (<anonymous>)\n    at ./node_modules/graphql-anywhere/lib/async.js.__awaiter (http://localhost:3000/static/js/bundle.js:9010:16)\n    at executeField$1 (http://localhost:3000/static/js/bundle.js:9145:16)\n    at http://localhost:3000/static/js/bundle.js:9098:62\n    at step (http://localhost:3000/static/js/bundle.js:9039:27)\n    at Object.next (http://localhost:3000/static/js/bundle.js:9020:57)\n    at http://localhost:3000/static/js/bundle.js:9014:75\n    at new Promise (<anonymous>)\n    at ./node_modules/graphql-anywhere/lib/async.js.__awaiter (http://localhost:3000/static/js/bundle.js:9010:16)\n    at execute (http://localhost:3000/static/js/bundle.js:9088:65)\n    at Array.map (<anonymous>)\n    at http://localhost:3000/static/js/bundle.js:9133:82\n    at step (http://localhost:3000/static/js/bundle.js:9039:27)\n    at Object.next (http://localhost:3000/static/js/bundle.js:9020:57)\n    at http://localhost:3000/static/js/bundle.js:9014:75\n    at new Promise (<anonymous>)\n    at ./node_modules/graphql-anywhere/lib/async.js.__awaiter (http://localhost:3000/static/js/bundle.js:9010:16)\n    at executeSelectionSet$1 (http://localhost:3000/static/js/bundle.js:9080:16)\n    at graphql$1 (http://localhost:3000/static/js/bundle.js:9077:16)\n    at Object.next (http://localhost:3000/static/js/bundle.js:5597:100)\n    at notifySubscription (http://localhost:3000/static/js/bundle.js:55341:18)\n    at onNotify (http://localhost:3000/static/js/bundle.js:55376:3)\n    at SubscriptionObserver.next (http://localhost:3000/static/js/bundle.js:55430:7)\n    at http://localhost:3000/static/js/bundle.js:5369:26"
```

Which might not be much help either way. I'm on the latest versions of Apollo Boost.

**Comment by stolinski** [comment]
Reproduction found here: 

https://github.com/stolinski/local-remote-link-state

**Comment by lorensr** [comment]
Atm you need a `resolvers` object:

```js
  clientState: {
    defaults: defaultState,
    resolvers: {}
  }
```

Thanks for reporting—we should probably remove this requirement 😊

**Comment by stolinski** [comment]
Makes total sense. I guess either removing that requirement or changing the docs here: 
https://www.apollographql.com/docs/react/essentials/local-state.html#setup

"None of these options are required. If you don’t specify anything, you will still be able to use the @client directive to query the cache."

Would make it more clear.

**Comment by lorensr** [comment]
Ha, yes. I'll do the former now. Also, your font size freaked me out—thought there was something seriously messed up with my VS Code 😆 Perhaps `echo ".vscode" >> ~/.gitignore`? 😁

**Comment by stolinski** [comment]
Good call! This code is or a course so it was at screen recoding size. I totally forgot that I would have committed that. 😂😅
